# Generated by Django 6.0.1 on 2026-01-08 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(choices=[('GRATIS', 'Gratuito'), ('PREMIUM', 'Premium')], max_length=20, unique=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_imoveis', models.PositiveIntegerField(help_text='Quantidade máxima de imóveis ativos permitidos')),
                ('max_fotos_por_imovel', models.PositiveIntegerField(default=5)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Anunciante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('telefone', models.CharField(max_length=20, verbose_name='WhatsApp/Telefone')),
                ('creci', models.CharField(blank=True, help_text='Obrigatório para corretores', max_length=20)),
                ('bio', models.TextField(blank=True, verbose_name='Sobre o Anunciante')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Perfil Aprovado?')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anunciante_profile', to=settings.AUTH_USER_MODEL)),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.plano')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
