# Generated by Django 6.0.1 on 2026-01-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anunciante',
            name='bairro_atuacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro de Foco (Ex: Tatuapé)'),
        ),
        migrations.AddField(
            model_name='plano',
            name='dias_de_anuncio',
            field=models.PositiveIntegerField(default=90, help_text='Tempo antes do anúncio expirar'),
        ),
        migrations.AddField(
            model_name='plano',
            name='dias_de_destaque',
            field=models.PositiveIntegerField(default=0, help_text='Quantos dias fica no topo?'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='max_fotos_por_imovel',
            field=models.PositiveIntegerField(default=20, help_text='O CEO pediu foco em qualidade visual'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='nome',
            field=models.CharField(choices=[('START', 'Start (Grátis 60 dias)'), ('BRONZE', 'Bronze (Individual)'), ('PRATA', 'Prata (Corretor)'), ('OURO', 'Ouro (Top Seller)'), ('IMOB_SMALL', 'Imobiliária Small'), ('IMOB_PRO', 'Imobiliária Pro'), ('IMOB_PREMIUM', 'Imobiliária Premium')], max_length=20, unique=True),
        ),
    ]
