# Generated by Django 6.0.1 on 2026-01-08 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('descricao', models.TextField()),
                ('tipo_imovel', models.CharField(choices=[('CASA', 'Casa'), ('APARTAMENTO', 'Apartamento'), ('COBERTURA', 'Cobertura'), ('TERRENO', 'Terreno'), ('COMERCIAL', 'Comercial'), ('RURAL', 'Rural')], max_length=20)),
                ('tipo_transacao', models.CharField(choices=[('VENDA', 'Venda'), ('ALUGUEL', 'Aluguel')], max_length=20)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quartos', models.PositiveIntegerField(default=0)),
                ('banheiros', models.PositiveIntegerField(default=0)),
                ('vagas_garagem', models.PositiveIntegerField(default=0)),
                ('area_total', models.PositiveIntegerField(help_text='Em m²')),
                ('cep', models.CharField(max_length=9)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('PENDENTE', 'Aguardando Aprovação'), ('ATIVO', 'Ativo'), ('VENDIDO', 'Vendido/Alugado')], default='RASCUNHO', max_length=20)),
                ('destaque', models.BooleanField(default=False, help_text='Exibir na home como destaque?')),
                ('anunciante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imoveis', to='accounts.anunciante')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImovelImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('imagem', models.ImageField(upload_to='imoveis/%Y/%m/')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='imoveis.imovel')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('respondido', models.BooleanField(default=False)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='imoveis.imovel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='imovel',
            index=models.Index(fields=['status', 'tipo_transacao', 'cidade'], name='imoveis_imo_status_4ddf1c_idx'),
        ),
    ]
