# Generated by Django 6.0.1 on 2026-01-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='suites',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
