# Generated by Django 6.0.1 on 2026-01-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_imovel_suites'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='iptu',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='IPTU (Mensal)'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_condominio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Valor do Condomínio'),
        ),
    ]
