# Generated by Django 6.0.1 on 2026-01-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_imovel_iptu_imovel_valor_condominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='latitude',
            field=models.CharField(blank=True, help_text='Ex: -23.550520', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='longitude',
            field=models.CharField(blank=True, help_text='Ex: -46.633308', max_length=50, null=True),
        ),
    ]
